<?xml version="1.0"?>
<package format="2">
  <name>kuavo_camera_calibration</name>
  <version>0.0.0</version>
  <description>Kuavo camera chessboard calibration assets and launch files</description>
  <maintainer email="FanYunFu@lejurobot.com">Fandes</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>robot_calibration</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rospy</exec_depend>
</package>
