# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11robot_state.proto\"\'\n\x06Header\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\"F\n\x10\x45ndEffectorState\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x10\n\x08velocity\x18\x02 \x03(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x03 \x03(\x01\"@\n\nJointState\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x10\n\x08velocity\x18\x02 \x03(\x01\x12\x0e\n\x06torque\x18\x03 \x03(\x01\"l\n\nRobotState\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12#\n\x08\x65\x65_state\x18\x02 \x01(\x0b\x32\x11.EndEffectorState\x12 \n\x0bjoint_state\x18\x03 \x01(\x0b\x32\x0b.JointStateb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADER._serialized_start=21
  _HEADER._serialized_end=60
  _ENDEFFECTORSTATE._serialized_start=62
  _ENDEFFECTORSTATE._serialized_end=132
  _JOINTSTATE._serialized_start=134
  _JOINTSTATE._serialized_end=198
  _ROBOTSTATE._serialized_start=200
  _ROBOTSTATE._serialized_end=308
# @@protoc_insertion_point(module_scope)
