"""
Used to implement the InEKF filter for velocity estimation
The initial code is generated by Grok and modified according to our needs
"""

import numpy as np
from scipy.spatial.transform import Rotation as R


class SE23RightInEKF:
    """
    Right-Invariant EKF on SE₂(3) for 6-DoF velocity estimation.
    State: X = [ R  p  v ]
            [ 0  1  0 ]
            [ 0  0  1 ]   ∈ SE₂(3)
    - R  : rotation matrix (world → body)
    - p  : position in world frame
    - v  : linear velocity in body frame (common choice for right-invariant)
    """
    def __init__(self, nq: int, process_noise: dict | None = None):
        self.nq = nq  # full configuration size (xyz + wxyz + joints)
        self.nq_vel = nq - 1

        # State (5x5 matrix representation of SE₂(3))
        self.X = np.eye(5)                    # [R p v; 0 1 0; 0 0 1]
        self.X[:3, :3] = np.eye(3)            # initial orientation
        self.X[:3, 3] = 0.0                   # initial position
        self.X[:3, 4] = 0.0                   # initial body velocity

        # Covariance (12x12 on the Lie algebra se₂(3))
        self.P = np.eye(12) * 1e-6
        self.P[6:9, 6:9] *= 100.0   # higher initial uncertainty on velocity

        # Default process noise (tunable)
        default_noise = {
            'rot': 0.01,      # rad/s
            'vel': 0.1,       # m/s
            'pos': 1e-6,      # very low — we have direct pos measurements
        }
        self.noise = process_noise or default_noise
        self.Q = self._build_process_noise_matrix()

        self.initialized = False
        self.last_position = np.zeros(nq)

    def _build_process_noise_matrix(self):
        n = self.noise
        Q = np.zeros((12, 12))
        Q[0:3, 0:3] = np.eye(3) * (n['rot']**2)      # angular velocity noise
        Q[3:6, 3:6] = np.eye(3) * (n['vel']**2)      # velocity noise
        Q[6:9, 6:9] = np.eye(3) * (n['pos']**2)      # position noise (tiny)
        Q[9:12, 9:12] = np.eye(3) * (n['rot']**2)    # redundant rotation noise
        return Q

    def reset(self):
        self.__init__(self.nq, self.noise)

    def velocity_estimation(self, current_position: np.ndarray, dt: float | None = None) -> np.ndarray:
        """
        Args:
            current_position: [x,y,z, qw,qx,qy,qz, q1,q2,...,qn]
            dt: time since last call (seconds)
        Returns:
            velocity: [vx,vy,vz, wx,wy,wz, dq1/dt, ..., dqn/dt]  (body-frame linear vel, body-frame ang vel)
        """
        if dt is None or dt <= 1e-8:
            return np.zeros(self.nq_vel)

        pos_meas = current_position[:3]
        quat_meas = current_position[3:7]                    # wxyz
        joint_pos = current_position[7:]

        quat_meas = quat_meas / np.linalg.norm(quat_meas)
        R_meas = R.from_quat(quat_meas[[1,2,3,0]]).as_matrix()  # scipy: xyzw → matrix

        if not self.initialized:
            # Initialize state with first measurement
            self.X[:3, :3] = R_meas.T                               # R_world_to_body
            self.X[:3, 3] = pos_meas
            self.X[:3, 4] = np.zeros(3)                             # assume zero velocity
            self.last_position[:] = current_position
            self.initialized = True
            return np.zeros(self.nq_vel)

        # ========================= Prediction =========================
        # For pure kinematic updates with no IMU, we treat it as zero process input
        # (velocity is assumed constant in body frame between updates)
        theta = np.zeros(3)                      # no angular velocity input
        v = self.X[:3, 4]                        # current body velocity estimate

        # Exponential map for prediction (exact discrete propagation on SE₂(3))
        theta_skew = self._skew(theta)
        v_skew = self._skew(v)

        # SE₂(3) exponential (closed form)
        phi = np.eye(3)
        if np.linalg.norm(theta) > 1e-8:
            theta_norm = np.linalg.norm(theta)
            theta_skew = self._skew(theta)
            phi = (np.eye(3) + 
                   (1 - np.cos(theta_norm)) / (theta_norm**2) * theta_skew +
                   (theta_norm - np.sin(theta_norm)) / (theta_norm**3) * theta_skew @ theta_skew)

        J_left = np.eye(3)
        if np.linalg.norm(theta) > 1e-8:
            theta_norm = np.linalg.norm(theta)
            a = theta_norm / 2
            J_left = (np.sin(a) / a) * np.eye(3) + \
                     (1 - np.sin(a) / a) * (theta @ theta.T) / (theta_norm**2) + \
                     (1 - np.cos(a)) / (2 * a**2) * theta_skew

        # Predicted translation increment
        delta_p = phi @ v * dt

        X_pred = np.eye(5)
        X_pred[:3, :3] = phi @ self.X[:3, :3]
        X_pred[:3, 3] = self.X[:3, 3] + delta_p
        X_pred[:3, 4] = v  # velocity stays constant (no acceleration model)

        # Propagate covariance (right-invariant error)
        Phi = np.eye(12)
        Phi[0:3, 0:3] = phi.T
        Phi[3:6, 0:3] = -phi.T @ v_skew @ dt
        Phi[6:9, 6:9] = phi.T
        Phi[3:6, 3:6] = np.eye(3)

        self.P = Phi @ self.P @ Phi.T + self.Q * dt

        self.X = X_pred

        # ========================= Measurement Update =========================
        # Direct measurements: world position and orientation
        H = np.zeros((6, 12))
        H[0:3, 6:9] = np.eye(3)                 # position measurement
        H[3:6, 0:3] = np.eye(3)                 # rotation measurement (on tangent space)

        z = np.zeros(6)
        z[0:3] = pos_meas
        z[3:6] = self._log_map(R_meas @ self.X[:3, :3].T)   # log(R_measured * R_predicted^T)

        y = z - H @ self._log_error(self.X)[:12]  # innovation (right-invariant)

        S = H @ self.P @ H.T + np.eye(6) * 1e-6
        K = self.P @ H.T @ np.linalg.solve(S, np.eye(6))

        delta = K @ y
        self.X = self._exp_map(delta) @ self.X
        self.P = (np.eye(12) - K @ H) @ self.P

        # ========================= Extract velocities =========================
        R_wb = self.X[:3, :3]           # world → body
        v_body = self.X[:3, 4].copy()

        # Angular velocity in body frame (from rotation part of error dynamics)
        # Since we have no gyro, we estimate it via finite difference on orientation (smoothed)
        q_curr = R.from_matrix(R_wb.T).as_quat()[[3,0,1,2]]  # wxyz
        q_last = R.from_quat(self.last_position[3:7][[1,2,3,0]]).as_quat()[[3,0,1,2]]
        delta_q = self._quat_multiply(q_curr, self._quat_conj(self.last_position[3:7]))
        delta_q /= np.linalg.norm(delta_q)
        angle = 2 * np.arccos(np.clip(delta_q[0], -1.0, 1.0))
        if abs(np.sin(angle/2)) < 1e-6:
            w_body = np.zeros(3)
        else:
            axis = delta_q[1:] / np.sin(angle/2)
            w_body = axis * (angle / dt)

        # Or more robust: use the filter's internal rotation rate (if you add gyro later, it will be accurate)
        # For now: use smoothed finite difference
        w_body_filtered = w_body  # you can low-pass this externally if needed

        joint_vel = (joint_pos - self.last_position[7:]) / dt

        velocity = np.concatenate([v_body, w_body_filtered, joint_vel])

        # Save for next cycle
        self.last_position[:] = current_position

        return velocity

    # ====================== Helper functions ======================
    @staticmethod
    def _skew(v):
        return np.array([[0, -v[2], v[1]],
                         [v[2], 0, -v[0]],
                         [-v[1], v[0], 0]])

    @staticmethod
    def _log_map(R):
        """SO(3) log map → axis-angle vector"""
        trace = np.clip(R.trace(), -1.0, 3.0)
        if trace > 3.0 - 1e-6:
            return np.zeros(3)
        angle = np.arccos((trace - 1) / 2)
        return angle / (2 * np.sin(angle)) * np.array([R[2,1]-R[1,2], R[0,2]-R[2,0], R[1,0]-R[0,1]])

    @staticmethod
    def _log_error(X):
        """Right-invariant error ξ = log(X^{-1} ⊕ X̂) ∈ se₂(3)"""
        R = X[:3, :3]
        p = X[:3, 3]
        v = X[:3, 4]
        theta = SE23RightInEKF._log_map(R)
        xi = np.zeros(12)
        xi[0:3] = theta
        xi[3:6] = v
        xi[6:9] = p
        return xi

    @staticmethod
    def _exp_map(xi):
        """Exponential map se₂(3) → SE₂(3)"""
        theta = xi[0:3]
        v = xi[3:6]
        p = xi[6:9]

        theta_norm = np.linalg.norm(theta)
        theta_skew = SE23RightInEKF._skew(theta)

        if theta_norm < 1e-8:
            R = np.eye(3)
            V = np.eye(3)
        else:
            sin_t = np.sin(theta_norm)
            cos_t = np.cos(theta_norm)
            R = (np.eye(3) +
                 (1 - cos_t) / (theta_norm**2) * theta_skew +
                 (theta_norm - sin_t) / (theta_norm**3) * theta_skew @ theta_skew)
            V = (np.eye(3) +
                 (1 - cos_t) / (theta_norm**2) * theta_skew +
                 (theta_norm - sin_t) / (theta_norm**3) * theta_skew @ theta_skew)

        Xnew = np.eye(5)
        Xnew[:3, :3] = R
        Xnew[:3, 3] = V @ p
        Xnew[:3, 4] = V @ v
        return Xnew

    @staticmethod
    def _quat_multiply(q1, q2):
        w1, x1, y1, z1 = q1
        w2, x2, y2, z2 = q2
        return np.array([
            w1*w2 - x1*x2 - y1*y2 - z1*z2,
            w1*x2 + x1*w2 + y1*z2 - z1*y2,
            w1*y2 - x1*z2 + y1*w2 + z1*x2,
            w1*z2 + x1*y2 - y1*x2 + z1*w2,
        ])

    @staticmethod
    def _quat_conj(q):
        return np.array([q[0], -q[1], -q[2], -q[3]])
