- name: safe_pose
  position:
    - [[0, 0.3], [100, 0.3]]
    - [[0, -0.15], [100, -0.15]]
    - [[0, 0.37], [100, 0.6]]
    - [[0, 0], [100, 0]]
    - [[0, 0], [100, 0]]
    - [[0, 0.37], [100, 0.37]]
    - [[0, 0], [100, 0]]
    - [[0, 0.37], [100, 0.37]]
    - [[0, 0], [100, 0]]
    - [[0, 0], [100, 0]]
    - [[0, 0.37], [100, 0.37]]
  torque_ff:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  kp:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  kd:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  output_limit:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  mode:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []