#pragma once

#include <cmath>

#ifndef ENABLE_RL_TO_RL_INTERPOLATION
#define ENABLE_RL_TO_RL_INTERPOLATION 1
#endif

#ifndef RL_TO_RL_USE_CONTINUOUS_DUAL_INFERENCE
#define RL_TO_RL_USE_CONTINUOUS_DUAL_INFERENCE 1
#endif

#ifndef RL_TO_RL_USE_KD_LOCK
#define RL_TO_RL_USE_KD_LOCK 0
#endif

#ifndef RL_TO_RL_USE_WARM_RESUME
#define RL_TO_RL_USE_WARM_RESUME 1
#endif

#ifndef RL_TO_RL_SWITCH_DURATION_DEFAULT
#define RL_TO_RL_SWITCH_DURATION_DEFAULT 0.5
#endif

// VMP->AMP 双边插值时，AMP 冷启动后先预热再参与混合（秒）
#ifndef RL_TO_RL_VMP_AMP_TARGET_WARMUP_DURATION_DEFAULT
#define RL_TO_RL_VMP_AMP_TARGET_WARMUP_DURATION_DEFAULT 0.15
#endif

// RL→MPC joint_cmd 续接时长
#ifndef CONTROLLER_CMD_BLEND_DURATION_DEFAULT
#define CONTROLLER_CMD_BLEND_DURATION_DEFAULT 0.2
#endif

#ifndef RL_TO_RL_PHASE_SYNC_PHI_THRESH_RAD_DEFAULT
#define RL_TO_RL_PHASE_SYNC_PHI_THRESH_RAD_DEFAULT (0.2 * M_PI)
#endif

#ifndef RL_TO_RL_PHASE_SYNC_SIN_GUARD_DEFAULT
#define RL_TO_RL_PHASE_SYNC_SIN_GUARD_DEFAULT 0.2
#endif

#ifndef RL_TO_RL_PHASE_SYNC_K0_DEFAULT
#define RL_TO_RL_PHASE_SYNC_K0_DEFAULT 2.0
#endif

#ifndef RL_TO_RL_PHASE_SYNC_DECAY_POWER_DEFAULT
#define RL_TO_RL_PHASE_SYNC_DECAY_POWER_DEFAULT 1.0
#endif

#ifndef RL_TO_RL_PHASE_SYNC_FREQUENCY_MIN_HZ_DEFAULT
#define RL_TO_RL_PHASE_SYNC_FREQUENCY_MIN_HZ_DEFAULT 0.8
#endif

#ifndef RL_TO_RL_PHASE_SYNC_FREQUENCY_MAX_HZ_DEFAULT
#define RL_TO_RL_PHASE_SYNC_FREQUENCY_MAX_HZ_DEFAULT 1.2
#endif

#ifndef RL_TO_RL_VELOCITY_DIP_ENABLED_DEFAULT
#define RL_TO_RL_VELOCITY_DIP_ENABLED_DEFAULT 1
#endif

#ifndef RL_TO_RL_VELOCITY_DIP_MIN_SCALE_DEFAULT
#define RL_TO_RL_VELOCITY_DIP_MIN_SCALE_DEFAULT 0.35
#endif

#ifndef RL_TO_RL_VELOCITY_DIP_MIDPOINT_DEFAULT
#define RL_TO_RL_VELOCITY_DIP_MIDPOINT_DEFAULT 0.45
#endif

#ifndef RL_SWITCH_WALKING_KNEE_DIFF_GUARD_ENABLED_DEFAULT
#define RL_SWITCH_WALKING_KNEE_DIFF_GUARD_ENABLED_DEFAULT 1
#endif

#ifndef RL_SWITCH_WALKING_KNEE_DIFF_MIN_RAD_DEFAULT
#define RL_SWITCH_WALKING_KNEE_DIFF_MIN_RAD_DEFAULT 0.2
#endif

#ifndef RL_SWITCH_WALKING_KNEE_DIFF_MAX_RAD_DEFAULT
#define RL_SWITCH_WALKING_KNEE_DIFF_MAX_RAD_DEFAULT 0.55
#endif

#ifndef RL_SWITCH_IN_PLACE_KNEE_DIFF_MIN_RAD_DEFAULT
#define RL_SWITCH_IN_PLACE_KNEE_DIFF_MIN_RAD_DEFAULT 0.002
#endif

#ifndef RL_SWITCH_IN_PLACE_KNEE_DIFF_MAX_RAD_DEFAULT
#define RL_SWITCH_IN_PLACE_KNEE_DIFF_MAX_RAD_DEFAULT 0.2
#endif

#ifndef RL_SWITCH_LEFT_KNEE_INDEX_DEFAULT
#define RL_SWITCH_LEFT_KNEE_INDEX_DEFAULT 2
#endif

#ifndef RL_SWITCH_RIGHT_KNEE_INDEX_DEFAULT
#define RL_SWITCH_RIGHT_KNEE_INDEX_DEFAULT 8
#endif

// RL switch motion-state classification.
#ifndef RL_SWITCH_STATIONARY_HOLD_TIME_DEFAULT
#define RL_SWITCH_STATIONARY_HOLD_TIME_DEFAULT 0.3
#endif

#ifndef RL_SWITCH_STATIONARY_COMMAND_LINEAR_THRESHOLD_DEFAULT
#define RL_SWITCH_STATIONARY_COMMAND_LINEAR_THRESHOLD_DEFAULT 0.03
#endif

#ifndef RL_SWITCH_STATIONARY_COMMAND_ANGULAR_THRESHOLD_DEFAULT
#define RL_SWITCH_STATIONARY_COMMAND_ANGULAR_THRESHOLD_DEFAULT 0.08
#endif

#ifndef RL_SWITCH_STATIONARY_TORSO_LINEAR_VELOCITY_THRESHOLD_DEFAULT
#define RL_SWITCH_STATIONARY_TORSO_LINEAR_VELOCITY_THRESHOLD_DEFAULT 0.05
#endif

#ifndef RL_SWITCH_STATIONARY_FOOT_FORCE_WEIGHT_RATIO_DEFAULT
#define RL_SWITCH_STATIONARY_FOOT_FORCE_WEIGHT_RATIO_DEFAULT 0.25
#endif
